baseURL: "https://brianpfeil.com/"
disablePathToLower: true
languageCode: "en-us"
title: "Brian Pfeil"
theme: "beautifulhugo"

pygmentsStyle: "trac"
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

googleAnalytics: "UA-610553-4"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  description: ""
  customCss: ["css/custom.css"]
  subtitle: ""
  mainSections: ["post", "posts"]
  #favicon: "img/favicon.ico"
  commit: false
  rss: true
  comments: true
  useHLJS: true
  socialShare: true
  delayDisqus: true
  showRelatedPosts: true
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  # dateFormat: "January 2, 2006"
  #readingTime: true
  #wordCount: true

Menus:
  main:
    - Name: "about"
      URL: "/about/"
      weight: 10
    - Name: "posts"
      URL: "/"
      weight: 20
    - Name: "projects"
      URL: "/projects/"
      weight: 30
    - Name: "notes"
      URL: "/notes/"
      weight: 40
