baseURL: "https://brianpfeil.com/"
disablePathToLower: true
languageCode: "en-us"
title: "Brian Pfeil"

buildFuture: true
pagination:
  pagerSize: 30

googleAnalytics: "UA-610553-4"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: trac
    lineNos: false
    noClasses: false

params:
  homeTitle: "Brian Pfeil"
  mainSections: ["post", "posts"]
  dateFormat: "January 2, 2006"
  rss: true
  rssLimit: 500
  author:
    name: "Brian Pfeil"
    website: "https://brianpfeil.com"
    github: "pfeilbr"
    twitter: "pfeilbr"
    stackoverflow: "users/29148/pfeilbr"

mediaTypes:
  text/plain:
    suffixes:
      - txt

outputFormats:
  llmstxt:
    mediaType: text/plain
    baseName: llms
    isPlainText: true
    notAlternative: true

outputs:
  home:
    - html
    - rss
    - json
    - llmstxt

menus:
  main:
    - name: "about"
      url: "/about/"
      weight: 10
    - name: "posts"
      url: "/"
      weight: 20
    - name: "projects"
      url: "/projects/"
      weight: 30
    - name: "tags"
      url: "/tags/"
      weight: 40
