baseURL = "https://brianpfeil.com/"
disablePathToLower = true
languageCode = "en-us"
title = "Brian Pfeil"
theme = "hyde"

googleAnalytics = "UA-610553-4"

[markup.goldmark.renderer]
unsafe= true

[params]
  description = "---"
  customCss = ["css/custom.css"]

[Menus]
  main = [
      {Name = "about", URL = "/about/"},
      {Name = "projects", URL = "/projects/"},
      {Name = "github", URL = "https://github.com/pfeilbr/"}
  ]
